export const ROUTES = {
  login: "/login",
  forgotPassword: "/esqueci-senha",
  resetPassword: "/redefinir-senha",
  forcedPasswordChange: "/trocar-senha",
  dashboard: "/dashboard",
  pipeline: "/pipeline",
  leads: "/leads",
  leadDetail: (id: string) => `/leads/${id}`,
  clientes: "/clientes",
  clienteDetail: (id: string) => `/clientes/${id}`,
  sdrCampanhas: "/sdr/campanhas",
  sdrCampanhaNova: "/sdr/campanhas/nova",
  sdrCampanhaEditar: (id: string) => `/sdr/campanhas/${id}`,
  sdrCampanhaExecucao: (campaignId: string, runId: string) =>
    `/sdr/campanhas/${campaignId}/execucoes/${runId}`,
  sdrPresets: "/sdr/presets",
  sdrCandidates: "/sdr/candidates",
  sdrCandidateDetail: (id: string) => `/sdr/candidates/${id}`,
  sdrCobertura: "/sdr/cobertura",
  tarefas: "/tarefas",
  agenda: "/agenda",
  relatorios: "/relatorios",
  configuracoes: "/configuracoes",
  usuarios: "/usuarios",
  perfil: "/perfil",
  terapeutaDaVez: "/terapeuta-da-vez",
  terapeutaDaVezGestao: "/terapeuta-da-vez/gestao",
} as const;
