export const ROUTES = {
  login: "/login",
  forgotPassword: "/esqueci-senha",
  resetPassword: "/redefinir-senha",
  forcedPasswordChange: "/trocar-senha",
  dashboard: "/dashboard",
  pipeline: "/pipeline",
  leads: "/leads",
  leadDetail: (id: string) => `/leads/${id}`,
  tarefas: "/tarefas",
  agenda: "/agenda",
  relatorios: "/relatorios",
  configuracoes: "/configuracoes",
  usuarios: "/usuarios",
  perfil: "/perfil",
  terapeutaDaVez: "/terapeuta-da-vez",
  terapeutaDaVezGestao: "/terapeuta-da-vez/gestao",
} as const;
