/** Sugestões de nicho pro campo da campanha (o campo continua aceitando
 * texto livre). Cada item tem categoria mapeada no backend
 * (`geoapify_category_mapper.py`) — nicho fora dessa lista falha no provider
 * Geoapify com "Sem categoria mapeada". Ao adicionar um nicho novo lá,
 * inclua aqui também. */
export const SDR_NICHE_SUGGESTIONS: readonly string[] = [
  "Academias",
  "Açougues",
  "Advocacia",
  "Agências de viagens",
  "Arquitetura",
  "Autoescolas",
  "Cabeleireiros",
  "Cartórios",
  "Clínicas médicas",
  "Clínicas odontológicas",
  "Consultoria",
  "Contabilidade",
  "Corretoras de seguros",
  "Dentistas",
  "Escolas",
  "Escolas de idiomas",
  "Escritórios de contabilidade",
  "Estética",
  "Farmácias",
  "Fotografia",
  "Hotéis",
  "Imobiliárias",
  "Lava rápido",
  "Lavanderias",
  "Oficinas mecânicas",
  "Óticas",
  "Padarias",
  "Pet shops",
  "Pizzarias",
  "Restaurantes",
  "Salões de beleza",
  "Veterinárias",
];
